### ISSUE TITLE
Fresh deployments are a bit unfriendly

### ISSUE THREAD

**Issue by WolfNT90** [ZeNyfh/gigavibe-java-edition#182]
**Describe the bug**

**To Reproduce**
1. Do a fresh `git clone`
2. Do `mvn package`
3. Attempt to run the generated jar
```
java.io.IOException: No such file or directory
	at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.base/java.io.File.createNewFile(File.java:1043)
	at Bots.GuildDataManager.CreateConfig(GuildDataManager.java:85)
	at Bots.GuildDataManager.CreateConfig(GuildDataManager.java:94)
	at Bots.GuildDataManager.GetConfig(GuildDataManager.java:175)
	at Bots.Main.<clinit>(Main.java:75)
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.NullPointerException
	at Bots.GuildDataManager.GetConfig(GuildDataManager.java:181)
	at Bots.Main.<clinit>(Main.java:75)
```

**Expected behavior**
README.md#Usage
"If there is no .env file, try running the bot once. It will proceed to create any missing files."

**Additional context**
Creating a folder called `config` next to the generated jar "fixes" the problem:
```
2024/08/20 07:14:25 | Exception in thread "main" io.github.cdimascio.dotenv.DotenvException: Could not find /.env on the classpath
2024/08/20 07:14:25 | 	at io.github.cdimascio.dotenv.internal.ClasspathHelper.loadFileFromClasspath(ClasspathHelper.java:26)
2024/08/20 07:14:25 | 	at io.github.cdimascio.dotenv.internal.DotenvReader.read(DotenvReader.java:57)
2024/08/20 07:14:25 | 	at io.github.cdimascio.dotenv.internal.DotenvParser.lines(DotenvParser.java:65)
2024/08/20 07:14:25 | 	at io.github.cdimascio.dotenv.internal.DotenvParser.parse(DotenvParser.java:47)
2024/08/20 07:14:25 | 	at io.github.cdimascio.dotenv.DotenvBuilder.load(DotenvBuilder.java:77)
2024/08/20 07:14:25 | 	at io.github.cdimascio.dotenv.Dotenv.load(Dotenv.java:38)
2024/08/20 07:14:25 | 	at Bots.Main.main(Main.java:91)
2024/08/20 07:14:25 | 	Suppressed: io.github.cdimascio.dotenv.DotenvException: Could not find ./.env on the file system (working directory: /home/fox/Triage/gigavibe-java-edition)
2024/08/20 07:14:25 | 		at io.github.cdimascio.dotenv.internal.DotenvReader.read(DotenvReader.java:62)
2024/08/20 07:14:25 | 		... 5 more
```
and then it doesn't exit after this. Need to CTRL-C in terminal.

**Comment by 9382** [comment]
Fixed both the missing folder issue and the non-terminating issue. Probably should've tested the first-run experience a bit more at the time
